name: llm_disinfo
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.9
  - pytorch==1.13.1
  - torchvision==0.14.1
  - pytorch-cuda=11.7
  - ca-certificates
  - openssl
  - fasttext==0.9.2
  - umap-learn==0.5.3
  - pandas==1.5.3
  - tqdm==4.65.0
  - transformers==4.28.1
  - scikit-learn==1.2.2
  - ipykernel==6.21.3
  - ipywidgets==8.0.4
  - numpy==1.23.5
  - scipy==1.10.1
  - huggingface_hub==0.13.1
  - hdbscan==0.8.29
  - sentence-transformers==2.2.2
  - sentencepiece-python==0.1.97
  - certifi
  - plotly==5.13.1
  - pyparsing==3.1.2
  - pip:
    - bertopic==0.14.1
